# -*- mode: ruby -*-
# vi: set ft=ruby :

$installScript = <<SCRIPT
echo "Installing dependencies ..."
sudo apt-get update
sudo apt-get install -y unzip curl jq screen

sudo cp -R /vagrant/consul.d /etc/
sudo chmod a+w /etc/consul.d
sudo cp /vagrant/consul /usr/bin

export PATH=$PATH:/usr/local/bin
sudo apt-get install -y nodejs npm && npm install -g http-server
sudo ln -s /usr/bin/nodejs /bin/nodejs
sudo ln -s /usr/bin/npm /bin/npm
SCRIPT


$server = <<SCRIPT
sudo chmod 0700 /etc/consul.d/ssl/CA
sudo nohup consul agent -server -bootstrap-expect=1 -data-dir=/tmp/consul -node=agent-one -bind=172.20.20.10 -config-dir=/etc/consul.d &>consul.log &
SCRIPT

$client = <<SCRIPT
echo '{"service": {"name": "web", "tags": ["rails"], "port": 80}}' >> /etc/consul.d/web.json && \
sudo nohup consul agent -data-dir=/tmp/consul -node=agent-two -bind=172.20.20.11 -config-dir=/etc/consul.d &>consul.log &
SCRIPT

$clientJoin = <<SCRIPT
consul join 172.20.20.10
SCRIPT

# Specify a custom Vagrant box for the demo
DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "debian/jessie64"

# Vagrantfile API/syntax version.
# NB: Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = DEMO_BOX_NAME
  config.vm.synced_folder '.', '/vagrant', disabled: true

  #config.vm.synced_folder 'usr/bin', '/vagrant/usr/bin/'

  #config.vm.provision "file", source: "consul", destination: "/usr/bin"

  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
	  n1.vm.synced_folder 'build/server', '/vagrant'
      n1.vm.network "private_network", ip: "172.20.20.10"
      n1.vm.provision "shell", "inline": $installScript
      n1.vm.provision "shell", "inline": $server
  end

  config.vm.define "n2" do |n2|
      n2.vm.hostname = "n2"
	  n2.vm.synced_folder 'build/client', '/vagrant'
      n2.vm.network "private_network", ip: "172.20.20.11"
      n2.vm.provision "shell", "inline": $installScript
      n2.vm.provision "shell", "inline": $client
      n2.vm.provision "shell", "inline": $clientJoin
  end
end
